---
- name: Create NZBget Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ nzbget_config_directory }}"
    - "{{ downloads_root }}/nzbget"

- name: Create NZBget Container
  docker_container:
    name: nzbget
    image: linuxserver/nzbget
    pull: true
    volumes:
      - "{{ movies_root }}:/movies:rw"
      - "{{ tv_root }}:/tv:rw"
      - "{{ downloads_root }}:/downloads"
      - "{{ nzbget_config_directory }}:/config"
    ports:
      - "6789:6789"
    env:
      TZ: "{{ ansible_nas_timezone }}"
      PUID: "{{ nzbget_user_id }}"
      PGID: "{{ nzbget_group_id }}"
    restart_policy: unless-stopped
    memory: 1g
