---
- name: Create SABnzbd Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ sabnzbd_config_directory }}"
    - "{{ downloads_root }}/sabnzbd/complete"
    - "{{ downloads_root }}/sabnzbd/incomplete"
    - "{{ downloads_root }}/sabnzbd/scripts"
    - "{{ downloads_root }}/sabnzbd/watch"

- name: Create SABnzbd Container
  docker_container:
    name: sabnzbd
    image: linuxserver/sabnzbd
    hostname: "{{ ansible_nas_hostname }}.{{ ansible_nas_domain }}"
    pull: true
    volumes:
      - "{{ movies_root }}:/movies"
      - "{{ tv_root }}:/tv"
      - "{{ sabnzbd_config_directory }}:/config"
      - "{{ downloads_root }}:/downloads"
      - "{{ downloads_root }}/sabnzbd/incomplete:/incomplete-downloads"
    ports:
      - "8181:8080"
      - "9191:9090"
    env:
      TZ: "{{ ansible_nas_timezone }}"
      PUID: "{{ sabnzbd_user_id }}"
      PGID: "{{ sabnzbd_group_id }}"
    restart_policy: unless-stopped
    memory: 1g

- name: Stop SABnzbd Container
  docker_container:
    name: sabnzbd
    state: stopped

- name: Set SABnzbd watch folder
  ini_file:
    path: "{{ sabnzbd_config_directory }}/sabnzbd.ini"
    section: misc
    option: dirscan_dir
    value: "/downloads/sabnzbd/watch"

- name: Set SABnzbd scripts folder
  ini_file:
    path: "{{ sabnzbd_config_directory }}/sabnzbd.ini"
    section: misc
    option: script_dir
    value: "/downloads/sabnzbd/scripts"

- name: Set SABnzbd incomplete folder
  ini_file:
    path: "{{ sabnzbd_config_directory }}/sabnzbd.ini"
    section: misc
    option: download_dir
    value: "/incomplete-downloads"

- name: Set SABnzbd complete folder
  ini_file:
    path: "{{ sabnzbd_config_directory }}/sabnzbd.ini"
    section: misc
    option: complete_dir
    value: "/downloads/sabnzbd/complete"

- name: Start SABnzbd Container
  docker_container:
    name: sabnzbd
    state: started