---
- name: Create SABnzbd Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ sabnzbd_config_directory }}"
    - "{{ sabnzbd_downloads_directory }}"

- name: Create SABnzbd Container
  docker_container:
    name: sabnzbd
    image: linuxserver/sabnzbd
    hostname: "{{ ansible_nas_hostname }}.{{ ansible_nas_domain }}" 
    pull: true
    volumes:
      - "{{ movies_root }}:/movies:rw"
      - "{{ tv_root }}:/tv:rw"
      - "{{ sabnzbd_downloads_directory }}:/downloads:rw"
      - "{{ sabnzbd_config_directory }}:/config:rw"
    ports:
      - "8181:8080"
      - "9191:9090"
    env:
      TZ: "{{ ansible_nas_timezone }}"
      PUID: "{{ sabnzbd_user_id }}"
      PGID: "{{ sabnzbd_group_id }}"
    restart_policy: unless-stopped
    memory: 1g
