---
- name: Include VPN credentials
  include_vars: group_vars/vpn_credentials.yml

- name: Create Transmission Directories
  file:
    path: "{{ item }}"
    state: directory
    # mode: 0755
  with_items:
    - "{{ transmission_config_directory }}"
    - "{{ downloads_root }}/transmission"
    - "{{ torrents_root }}"

- name: Transmission with VPN
  docker_container:
    name: transmission-openvpn
    image: haugene/transmission-openvpn
    pull: true
    volumes:
      - "{{ transmission_config_directory }}:/config"
      - "{{ downloads_root }}:/downloads"
      - "{{ torrents_root }}:/watch"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - "9091:9091"
      - "51413:51413"
    env:
      TRANSMISSION_HOME: /config
      TRANSMISSION_DOWNLOAD_DIR: /downloads/transmission/complete
      TRANSMISSION_INCOMPLETE_DIR: /downloads/transmission/incomplete
      TRANSMISSION_WATCH_DIR: /watch
      OPENVPN_PROVIDER: "{{ openvpn_provider }}"
      OPENVPN_USERNAME: "{{ openvpn_username }}"
      OPENVPN_PASSWORD: "{{ openvpn_password }}"
      OPENVPN_CONFIG: "{{ openvpn_config }}"
      PUID: "{{ transmission_user_id }}"
      PGID: "{{ transmission_group_id }}"
      LOCAL_NETWORK: "{{ transmission_local_network }}"
      ENABLE_UFW: false
    devices:
      - /dev/net/tun
    capabilities:
      - NET_ADMIN
    restart_policy: unless-stopped
    memory: 1g
    labels:
      traefik.backend: "transmission-openvpn"
      traefik.frontend.rule: "Host:transmission-openvpn.{{ ansible_nas_domain }}"
      traefik.enable: "{{ transmission_with_openvpn_available_externally }}"
      traefik.port: "9091"
  register: transmission_openvpn_container

- name: Stop current transmission container
  docker_container:
    name: transmission-openvpn
    state: stopped
  when: transmission_openvpn_container.changed
  tags:
    - skip_ansible_lint

# Check for folders in the old location
- name: Check for old transmission complete folder
  stat:
    path: "{{ downloads_root }}/complete"
  register: tcf

- name: Check for old transmission incomplete folder
  stat:
    path: "{{ downloads_root }}/incomplete"
  register: tif

- name: Move transmission complete folder to new location
  command: mv "{{ downloads_root }}/complete" "{{ downloads_root }}/transmission"
  when: tcf.stat.isdir is defined and tcf.stat.isdir
  register: tcf_move

- name: Move transmission incomplete folder to new location
  command: mv "{{ downloads_root }}/incomplete" "{{ downloads_root }}/transmission"
  when: tif.stat.isdir is defined and tif.stat.isdir
  register: tif_move

- name: Start Transmission OpenVPN Container
  docker_container:
    name: transmission-openvpn
    state: started