---
- name: Create Transmission Directories
  file:
    path: "{{ item }}"
    state: directory
    # mode: 0755
  with_items:
    - "{{ transmission_config_directory }}"
    - "{{ downloads_root }}/transmission"
    - "{{ torrents_root }}"

- name: Transmission Docker Container
  docker_container:
    name: transmission
    image: dperson/transmission
    state: started
    volumes:
      - "{{ transmission_config_directory }}:/var/lib/transmission-daemon/info"
      - "{{ downloads_root }}:/downloads"
      - "{{ torrents_root }}:/watch"
    ports:
      - "9092:9091"
      - "51414:51413"
    env:
      TZ: "{{ ansible_nas_timezone }}"
      USERID: "{{ transmission_user_id }}"
      GROUPID: "{{ transmission_group_id }}"
      TR_DOWNLOAD_DIR: "/downloads/transmission/complete"
      TR_INCOMPLETE_DIR: "/downloads/transmission/incomplete"
      TR_WATCH_DIR: "/watch"
    restart_policy: unless-stopped
    memory: 1g
  register: transmission_container
    labels:
      traefik.backend: "transmission"
      traefik.frontend.rule: "Host:transmission.{{ ansible_nas_domain }}"
      traefik.enable: "{{ transmission_available_externally }}"
      traefik.port: "9091"

- name: Wait for transmission container startup
  pause:
    seconds: 60
  when: transmission_container.changed
  tags:
    - skip_ansible_lint

# Brand new container requires a restart to correctly set
# changed download paths. Probably due to settings.json
# being missing on container creation
- name: Stop current transmission container
  docker_container:
    name: transmission
    state: stopped
  when: transmission_container.changed
  tags:
    - skip_ansible_lint

# Check for folders in the old location
- name: Check for old transmission complete folder
  stat:
    path: "{{ downloads_root }}/complete"
  register: tcf

- name: Check for old transmission incomplete folder
  stat:
    path: "{{ downloads_root }}/incomplete"
  register: tif

- name: Move transmission complete folder to new location
  command: mv "{{ downloads_root }}/complete" "{{ downloads_root }}/transmission"
  when: tcf.stat.isdir is defined and tcf.stat.isdir
  register: tcf_move

- name: Move transmission incomplete folder to new location
  command: mv "{{ downloads_root }}/incomplete" "{{ downloads_root }}/transmission"
  when: tif.stat.isdir is defined and tif.stat.isdir
  register: tif_move

- name: Start Transmission Container
  docker_container:
    name: transmission
    state: started