---
- name: Create Transmission Directories
  file:
    path: "{{ item }}"
    state: directory
    # mode: 0755
  with_items:
    - "{{ transmission_config_directory }}"
    - "{{ downloads_root }}/transmission"
    - "{{ torrents_root }}"

- name: Transmission Docker Container
  docker_container:
    name: transmission
    image: linuxserver/transmission
    pull: true
    state: started
    volumes:
      - "{{ transmission_config_directory }}:/config"
      - "{{ downloads_root }}:/downloads"
      - "{{ torrents_root }}:/watch"
    ports:
      - "9092:9091"
      - "51414:51413"
    env:
      TZ: "{{ ansible_nas_timezone }}"
      PUID: "{{ transmission_user_id }}"
      PGID: "{{ transmission_group_id }}"
    restart_policy: unless-stopped
    memory: 1g

- name: Stop Transmission Container
  docker_container:
    name: transmission
    state: stopped

- name: Enable Transmission User login
  replace:
    path: "{{ transmission_config_directory }}/settings.json"
    regexp: '^\s+"rpc-authentication-required": false,$'
    replace: '    "rpc-authentication-required": true,'

- name: Set Transmission Username
  replace:
    path: "{{ transmission_config_directory }}/settings.json"
    regexp: '^\s+"rpc-username": "",$'
    replace: '    "rpc-username": "admin",'

- name: Set Transmission Password
  replace:
    path: "{{ transmission_config_directory }}/settings.json"
    regexp: '^\s+"rpc-password": "{1ddd3f1f6a71d655cde7767242a23a575b44c909n5YuRT\.f",$'
    replace: '    "rpc-password": "admin",'

- name: Start Transmission Container
  docker_container:
    name: transmission
    state: started